---
openapi: 3.0.3
info:
  version: 1.1.4
  title: GitHub Actions API
  description: GitHub's v3 REST API for Actions.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: api.github.com
tags:
- name: actions
  description: Endpoints to manage GitHub Actions using the REST API.
servers:
- url: https://api.github.com
externalDocs:
  description: GitHub v3 REST API
  url: https://docs.github.com/rest/
paths:
  "/orgs/{org}/actions/cache/usage":
    get:
      summary: Get GitHub Actions cache usage for an organization
      description: |-
        Gets the total GitHub Actions cache usage for an organization.
        The data fetched using this API is refreshed approximately every 5 minutes, so values returned from this endpoint may take at least 5 minutes to get updated.

        OAuth tokens and personal access tokens (classic) need the `read:org` scope to use this endpoint.
      tags:
      - actions
      operationId: actions/get-actions-cache-usage-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/cache#get-github-actions-cache-usage-for-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/actions-cache-usage-org-enterprise"
              examples:
                default:
                  "$ref": "#/components/examples/actions-cache-usage-org-enterprise"
          headers:
            Link:
              "$ref": "#/components/headers/link"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: cache
  "/orgs/{org}/actions/cache/usage-by-repository":
    get:
      summary: List repositories with GitHub Actions cache usage for an organization
      description: |-
        Lists repositories and their GitHub Actions cache usage for an organization.
        The data fetched using this API is refreshed approximately every 5 minutes, so values returned from this endpoint may take at least 5 minutes to get updated.

        OAuth tokens and personal access tokens (classic) need the `read:org` scope to use this endpoint.
      tags:
      - actions
      operationId: actions/get-actions-cache-usage-by-repo-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/cache#list-repositories-with-github-actions-cache-usage-for-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      - "$ref": "#/components/parameters/per-page"
      - "$ref": "#/components/parameters/page"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                required:
                - total_count
                - repository_cache_usages
                properties:
                  total_count:
                    type: integer
                  repository_cache_usages:
                    type: array
                    items:
                      "$ref": "#/components/schemas/actions-cache-usage-by-repository"
              examples:
                default:
                  "$ref": "#/components/examples/org-actions-cache-usage-by-repo"
          headers:
            Link:
              "$ref": "#/components/headers/link"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: cache
  "/orgs/{org}/actions/hosted-runners":
    get:
      summary: List GitHub-hosted runners for an organization
      description: |-
        Lists all GitHub-hosted runners configured in an organization.

        OAuth app tokens and personal access tokens (classic) need the `manage_runner:org` scope to use this endpoint.
      tags:
      - actions
      operationId: actions/list-hosted-runners-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/hosted-runners#list-github-hosted-runners-for-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      - "$ref": "#/components/parameters/per-page"
      - "$ref": "#/components/parameters/page"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                required:
                - total_count
                - runners
                properties:
                  total_count:
                    type: integer
                  runners:
                    type: array
                    items:
                      "$ref": "#/components/schemas/actions-hosted-runner"
              examples:
                default:
                  "$ref": "#/components/examples/actions-hosted-runner-paginated"
          headers:
            Link:
              "$ref": "#/components/headers/link"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: hosted-runners
    post:
      summary: Create a GitHub-hosted runner for an organization
      description: |-
        Creates a GitHub-hosted runner for an organization.
        OAuth tokens and personal access tokens (classic) need the `manage_runners:org` scope to use this endpoint.
      operationId: actions/create-hosted-runner-for-org
      tags:
      - actions
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/hosted-runners#create-a-github-hosted-runner-for-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Name of the runner. Must be between 1 and 64 characters
                    and may only contain upper and lowercase letters a-z, numbers
                    0-9, '.', '-', and '_'.
                  type: string
                image:
                  description: The image of runner. To list all available images,
                    use `GET /actions/hosted-runners/images/github-owned` or `GET
                    /actions/hosted-runners/images/partner`.
                  type: object
                  properties:
                    id:
                      description: The unique identifier of the runner image.
                      type: string
                    source:
                      description: The source of the runner image.
                      type: string
                      enum:
                      - github
                      - partner
                      - custom
                size:
                  description: The machine size of the runner. To list available sizes,
                    use `GET actions/hosted-runners/machine-sizes`
                  type: string
                runner_group_id:
                  description: The existing runner group to add this runner to.
                  type: integer
                maximum_runners:
                  description: The maximum amount of runners to scale up to. Runners
                    will not auto-scale above this number. Use this setting to limit
                    your cost.
                  type: integer
                enable_static_ip:
                  description: Whether this runner should be created with a static
                    public IP. Note limit on account. To list limits on account, use
                    `GET actions/hosted-runners/limits`
                  type: boolean
              required:
              - name
              - image
              - size
              - runner_group_id
            examples:
              default:
                value:
                  name: my-runner
                  image:
                    id: ubuntu-22.04
                    source: github
                  size: 4-core
                  runner_group_id: 1
                  maximum_runners: 5
                  enable_static_ip: false
      responses:
        '201':
          description: Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/actions-hosted-runner"
              examples:
                default:
                  "$ref": "#/components/examples/actions-hosted-runner"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: hosted-runners
  "/orgs/{org}/actions/hosted-runners/images/github-owned":
    get:
      summary: Get GitHub-owned images for GitHub-hosted runners in an organization
      description: Get the list of GitHub-owned images available for GitHub-hosted
        runners for an organization.
      operationId: actions/get-hosted-runners-github-owned-images-for-org
      tags:
      - actions
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/hosted-runners#get-github-owned-images-for-github-hosted-runners-in-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                required:
                - total_count
                - images
                properties:
                  total_count:
                    type: integer
                  images:
                    type: array
                    items:
                      "$ref": "#/components/schemas/actions-hosted-runner-image"
              examples:
                default:
                  "$ref": "#/components/examples/actions-hosted-runner-image"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: hosted-runners
  "/orgs/{org}/actions/hosted-runners/images/partner":
    get:
      summary: Get partner images for GitHub-hosted runners in an organization
      description: Get the list of partner images available for GitHub-hosted runners
        for an organization.
      operationId: actions/get-hosted-runners-partner-images-for-org
      tags:
      - actions
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/hosted-runners#get-partner-images-for-github-hosted-runners-in-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                required:
                - total_count
                - images
                properties:
                  total_count:
                    type: integer
                  images:
                    type: array
                    items:
                      "$ref": "#/components/schemas/actions-hosted-runner-image"
              examples:
                default:
                  "$ref": "#/components/examples/actions-hosted-runner-image"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: hosted-runners
  "/orgs/{org}/actions/hosted-runners/limits":
    get:
      summary: Get limits on GitHub-hosted runners for an organization
      description: Get the GitHub-hosted runners limits for an organization.
      operationId: actions/get-hosted-runners-limits-for-org
      tags:
      - actions
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/hosted-runners#get-limits-on-github-hosted-runners-for-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/actions-hosted-runner-limits"
              examples:
                default:
                  "$ref": "#/components/examples/actions-hosted-runner-limits-default"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: hosted-runners
  "/orgs/{org}/actions/hosted-runners/machine-sizes":
    get:
      summary: Get GitHub-hosted runners machine specs for an organization
      description: Get the list of machine specs available for GitHub-hosted runners
        for an organization.
      operationId: actions/get-hosted-runners-machine-specs-for-org
      tags:
      - actions
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/hosted-runners#get-github-hosted-runners-machine-specs-for-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                required:
                - total_count
                - machine_specs
                properties:
                  total_count:
                    type: integer
                  machine_specs:
                    type: array
                    items:
                      "$ref": "#/components/schemas/actions-hosted-runner-machine-spec"
              examples:
                default:
                  "$ref": "#/components/examples/actions-hosted-runner-machine-spec"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: hosted-runners
  "/orgs/{org}/actions/hosted-runners/platforms":
    get:
      summary: Get platforms for GitHub-hosted runners in an organization
      description: Get the list of platforms available for GitHub-hosted runners for
        an organization.
      operationId: actions/get-hosted-runners-platforms-for-org
      tags:
      - actions
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/hosted-runners#get-platforms-for-github-hosted-runners-in-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                required:
                - total_count
                - platforms
                properties:
                  total_count:
                    type: integer
                  platforms:
                    type: array
                    items:
                      type: string
              examples:
                default:
                  value:
                    total_count: 1
                    platforms:
                    - linux-x64
                    - win-x64
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: hosted-runners
  "/orgs/{org}/actions/hosted-runners/{hosted_runner_id}":
    get:
      summary: Get a GitHub-hosted runner for an organization
      description: |-
        Gets a GitHub-hosted runner configured in an organization.

        OAuth app tokens and personal access tokens (classic) need the `manage_runners:org` scope to use this endpoint.
      tags:
      - actions
      operationId: actions/get-hosted-runner-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/actions/hosted-runners#get-a-github-hosted-runner-for-an-organization
      parameters:
      - "$ref": "#/components/parameters/org"
      - "$ref": "#/components/parameters/hosted-runner-id"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/actions-hosted-runner"
              examples:
                default:
                  "$ref": "#/components/examples/actions-hosted-runner"
          headers:
            Link:
              "$ref": "#/components/headers/link"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: actions
        subcategory: hosted-runners
components:
  parameters:
    org:
      name: org
      in: path
      required: true
      schema:
        type: string
      description: The organization name. The name is not case sensitive.
    per-page:
      name: per_page
      in: query
      schema:
        type: integer
        default: 30
        minimum: 1
        maximum: 100
      description: The number of results per page (max 100).
    page:
      name: page
      in: query
      schema:
        type: integer
        default: 1
        minimum: 1
      description: Page number of the results to fetch.
    hosted-runner-id:
      name: hosted_runner_id
      in: path
      required: true
      schema:
        type: integer
      description: The unique identifier of the GitHub-hosted runner.
  schemas:
    actions-cache-usage-org-enterprise:
      type: object
      properties:
        total_count:
          type: integer
          description: The count of active caches across all repositories of an enterprise or organization.
        total_size_in_bytes:
          type: integer
          description: The total size in bytes of all active caches across all repositories of an enterprise or organization.
      required:
      - total_count
      - total_size_in_bytes
    actions-cache-usage-by-repository:
      type: object
      properties:
        full_name:
          type: string
          description: The full name of the repository.
        active_caches_count:
          type: integer
          description: The count of active caches in the repository.
        active_caches_size_in_bytes:
          type: integer
          description: The total size in bytes of all active caches in the repository.
      required:
      - full_name
      - active_caches_count
      - active_caches_size_in_bytes
    actions-hosted-runner:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the runner.
        name:
          type: string
          description: The name of the runner.
        os:
          type: string
          description: The Operating System of the runner.
        status:
          type: string
          description: The status of the runner.
          enum:
          - online
          - offline
        busy:
          type: boolean
          description: Whether the runner is busy.
        labels:
          type: array
          description: The labels of the runner.
          items:
            type: object
            properties:
              id:
                type: integer
                description: Unique identifier of the label.
              name:
                type: string
                description: Name of the label.
              type:
                type: string
                description: Type of the label.
                enum:
                - read-only
                - custom
        runner_group_id:
          type: integer
          description: The ID of the runner group.
        runner_group_name:
          type: string
          description: The name of the runner group.
        image:
          "$ref": "#/components/schemas/nullable-actions-hosted-runner-pool-image"
        machine_spec:
          "$ref": "#/components/schemas/actions-hosted-runner-machine-spec"
      required:
      - id
      - name
      - os
      - status
      - busy
      - labels
      - runner_group_id
      - runner_group_name
    nullable-actions-hosted-runner-pool-image:
      type: object
      nullable: true
      properties:
        id:
          type: string
          description: The unique identifier of the runner image.
        source:
          type: string
          description: The source of the runner image.
          enum:
          - github
          - partner
          - custom
      required:
      - id
      - source
    actions-hosted-runner-machine-spec:
      type: object
      properties:
        cpu_cores:
          type: integer
          description: The number of CPU cores available.
        memory_in_mb:
          type: integer
          description: The amount of memory available in megabytes.
        disk_in_mb:
          type: integer
          description: The amount of disk space available in megabytes.
      required:
      - cpu_cores
      - memory_in_mb
      - disk_in_mb
    actions-hosted-runner-image:
      title: GitHub-hosted runner image details.
      description: Provides details of a hosted runner image
      type: object
      properties:
        id:
          description: The ID of the image. Use this ID for the `image` parameter
            when creating a new larger runner.
          type: string
          example: ubuntu-20.04
        platform:
          description: The operating system of the image.
          type: string
          example: linux-x64
        size_gb:
          description: Image size in GB.
          type: integer
          example: 86
        display_name:
          description: Display name for this image.
          type: string
          example: 20.04
        source:
          description: The image provider.
          type: string
          enum:
          - github
          - partner
          - custom
      required:
      - id
      - platform
      - size_gb
      - display_name
      - source
    actions-hosted-runner-limits:
      type: object
      properties:
        public_ips:
          title: Static public IP Limits for GitHub-hosted Hosted Runners.
          description: Provides details of static public IP limits for GitHub-hosted
            Hosted Runners
          type: object
          properties:
            maximum:
              type: integer
              description: The maximum number of static public IP addresses that can
                be used for Hosted Runners.
              example: 50
            current_usage:
              type: integer
              description: The current number of static public IP addresses in use
                by Hosted Runners.
              example: 17
          required:
          - maximum
          - current_usage
      required:
      - public_ips
  examples:
    actions-cache-usage-org-enterprise:
      value:
        total_count: 2
        total_size_in_bytes: 200
    actions-hosted-runner-image:
      value:
        id: ubuntu-20.04
        platform: linux-x64
        size_gb: 86
        display_name: '20.04'
        source: github
    actions-hosted-runner-limits-default:
      value:
        public_ips:
          current_usage: 17
          maximum: 50
    actions-hosted-runner-machine-spec:
      value:
        id: 4-core
        cpu_cores: 4
        memory_gb: 16
        storage_gb: 150
    org-actions-cache-usage-by-repo:
      value:
        total_count: 1
        repository_cache_usages:
        - full_name: octo-org/octo-repo
          active_caches_count: 2
          active_caches_size_in_bytes: 200
    actions-hosted-runner-paginated:
      value:
        total_count: 2
        runners:
        - id: 23
          name: MBP
          os: macos
          status: online
          busy: true
          labels:
          - id: 5
            name: self-hosted
            type: read-only
          - id: 7
            name: macos
            type: read-only
          - id: 11
            name: ARM64
            type: read-only
          runner_group_id: 1
          runner_group_name: Default
          image:
            id: ubuntu-22.04
            source: github
          machine_spec:
            cpu_cores: 4
            memory_in_mb: 8192
            disk_in_mb: 102400
        - id: 24
          name: my-runner
          os: linux
          status: offline
          busy: false
          labels:
          - id: 5
            name: self-hosted
            type: read-only
          - id: 7
            name: linux
            type: read-only
          - id: 20
            name: ubuntu
            type: read-only
          runner_group_id: 1
          runner_group_name: Default
          image:
            id: ubuntu-22.04
            source: github
          machine_spec:
            cpu_cores: 4
            memory_in_mb: 8192
            disk_in_mb: 102400
    actions-hosted-runner:
      value:
        id: 23
        name: MBP
        os: macos
        status: online
        busy: true
        labels:
        - id: 5
          name: self-hosted
          type: read-only
        - id: 7
          name: macos
          type: read-only
        - id: 11
          name: ARM64
          type: read-only
        runner_group_id: 1
        runner_group_name: Default
        image:
          id: ubuntu-22.04
          source: github
        machine_spec:
          cpu_cores: 4
          memory_in_mb: 8192
          disk_in_mb: 102400
  headers:
    link:
      schema:
        type: string
      description: Link to the next page of results
