openapi: 3.0.3
info:
  version: 1.1.4
  title: GitHub v3 REST API - billing
  description: GitHub's v3 REST API.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: api.github.com
tags:
  - name: billing
    description: Monitor charges and usage from Actions and Packages.
paths:
  /organizations/{org}/settings/billing/usage:
    get:
      summary: Get billing usage report for an organization
      description: |-
        Gets a report of the total usage for an organization. To use this endpoint, you must be an administrator of an organization within an enterprise or an organization account.

        **Note:** This endpoint is only available to organizations with access to the enhanced billing platform. For more information, see "[About the enhanced billing platform](https://docs.github.com/billing/using-the-new-billing-platform)."
      tags:
        - billing
      operationId: billing/get-github-billing-usage-report-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/billing/enhanced-billing#get-billing-usage-report-for-an-organization
      parameters:
        - $ref: "#/components/parameters/org"
        - $ref: "#/components/parameters/billing-usage-report-year"
        - $ref: "#/components/parameters/billing-usage-report-month"
        - $ref: "#/components/parameters/billing-usage-report-day"
        - $ref: "#/components/parameters/billing-usage-report-hour"
      responses:
        "200":
          $ref: "#/components/responses/billing_usage_report_org"
        "400":
          $ref: "#/components/responses/bad_request"
        "403":
          $ref: "#/components/responses/forbidden"
        "500":
          $ref: "#/components/responses/internal_error"
        "503":
          $ref: "#/components/responses/service_unavailable"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: billing
        subcategory: enhanced-billing
  /orgs/{org}/settings/billing/actions:
    get:
      summary: Get GitHub Actions billing for an organization
      description: |-
        Gets the summary of the free and paid GitHub Actions minutes used.

        Paid minutes only apply to workflows in private repositories that use GitHub-hosted runners. Minutes used is listed for each GitHub-hosted runner operating system. Any job re-runs are also included in the usage. The usage returned includes any minute multipliers for macOS and Windows runners, and is rounded up to the nearest whole minute. For more information, see "[Managing billing for GitHub Actions](https://docs.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-actions)".

        OAuth app tokens and personal access tokens (classic) need the `repo` or `admin:org` scope to use this endpoint.
      operationId: billing/get-github-actions-billing-org
      tags:
        - billing
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/billing/billing#get-github-actions-billing-for-an-organization
      parameters:
        - $ref: "#/components/parameters/org"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/actions-billing-usage"
              examples:
                default:
                  $ref: "#/components/examples/actions-billing-usage"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: billing
        subcategory: billing
  /orgs/{org}/settings/billing/packages:
    get:
      summary: Get GitHub Packages billing for an organization
      description: |-
        Gets the free and paid storage used for GitHub Packages in gigabytes.

        Paid minutes only apply to packages stored for private repositories. For more information, see "[Managing billing for GitHub Packages](https://docs.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-packages)."

        OAuth app tokens and personal access tokens (classic) need the `repo` or `admin:org` scope to use this endpoint.
      operationId: billing/get-github-packages-billing-org
      tags:
        - billing
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/billing/billing#get-github-packages-billing-for-an-organization
      parameters:
        - $ref: "#/components/parameters/org"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/packages-billing-usage"
              examples:
                default:
                  $ref: "#/components/examples/packages-billing-usage"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: billing
        subcategory: billing
  /orgs/{org}/settings/billing/shared-storage:
    get:
      summary: Get shared storage billing for an organization
      description: |-
        Gets the estimated paid and estimated total storage used for GitHub Actions and GitHub Packages.

        Paid minutes only apply to packages stored for private repositories. For more information, see "[Managing billing for GitHub Packages](https://docs.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-packages)."

        OAuth app tokens and personal access tokens (classic) need the `repo` or `admin:org` scope to use this endpoint.
      operationId: billing/get-shared-storage-billing-org
      tags:
        - billing
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/billing/billing#get-shared-storage-billing-for-an-organization
      parameters:
        - $ref: "#/components/parameters/org"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/combined-billing-usage"
              examples:
                default:
                  $ref: "#/components/examples/combined-billing-usage"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: billing
        subcategory: billing
  /users/{username}/settings/billing/actions:
    get:
      summary: Get GitHub Actions billing for a user
      description: |-
        Gets the summary of the free and paid GitHub Actions minutes used.

        Paid minutes only apply to workflows in private repositories that use GitHub-hosted runners. Minutes used is listed for each GitHub-hosted runner operating system. Any job re-runs are also included in the usage. The usage returned includes any minute multipliers for macOS and Windows runners, and is rounded up to the nearest whole minute. For more information, see "[Managing billing for GitHub Actions](https://docs.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-actions)".

        OAuth app tokens and personal access tokens (classic) need the `user` scope to use this endpoint.
      operationId: billing/get-github-actions-billing-user
      tags:
        - billing
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/billing/billing#get-github-actions-billing-for-a-user
      parameters:
        - $ref: "#/components/parameters/username"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/actions-billing-usage"
              examples:
                default:
                  $ref: "#/components/examples/actions-billing-usage"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: billing
        subcategory: billing
  /users/{username}/settings/billing/packages:
    get:
      summary: Get GitHub Packages billing for a user
      description: |-
        Gets the free and paid storage used for GitHub Packages in gigabytes.

        Paid minutes only apply to packages stored for private repositories. For more information, see "[Managing billing for GitHub Packages](https://docs.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-packages)."

        OAuth app tokens and personal access tokens (classic) need the `user` scope to use this endpoint.
      operationId: billing/get-github-packages-billing-user
      tags:
        - billing
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/billing/billing#get-github-packages-billing-for-a-user
      parameters:
        - $ref: "#/components/parameters/username"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/packages-billing-usage"
              examples:
                default:
                  $ref: "#/components/examples/packages-billing-usage"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: billing
        subcategory: billing
  /users/{username}/settings/billing/shared-storage:
    get:
      summary: Get shared storage billing for a user
      description: |-
        Gets the estimated paid and estimated total storage used for GitHub Actions and GitHub Packages.

        Paid minutes only apply to packages stored for private repositories. For more information, see "[Managing billing for GitHub Packages](https://docs.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-packages)."

        OAuth app tokens and personal access tokens (classic) need the `user` scope to use this endpoint.
      operationId: billing/get-shared-storage-billing-user
      tags:
        - billing
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/billing/billing#get-shared-storage-billing-for-a-user
      parameters:
        - $ref: "#/components/parameters/username"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/combined-billing-usage"
              examples:
                default:
                  $ref: "#/components/examples/combined-billing-usage"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: billing
        subcategory: billing
  /users/{username}/settings/billing/usage:
    get:
      summary: Get billing usage report for a user
      description: >-
        Gets a report of the total usage for a user.


        **Note:** This endpoint is only available to users with access to the
        enhanced billing platform.
      tags:
        - billing
      operationId: billing/get-github-billing-usage-report-user
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/billing/enhanced-billing#get-billing-usage-report-for-a-user
      parameters:
        - $ref: "#/components/parameters/username"
        - $ref: "#/components/parameters/billing-usage-report-year"
        - $ref: "#/components/parameters/billing-usage-report-month"
        - $ref: "#/components/parameters/billing-usage-report-day"
        - $ref: "#/components/parameters/billing-usage-report-hour"
      responses:
        "200":
          $ref: "#/components/responses/billing_usage_report_user"
        "400":
          $ref: "#/components/responses/bad_request"
        "403":
          $ref: "#/components/responses/forbidden"
        "500":
          $ref: "#/components/responses/internal_error"
        "503":
          $ref: "#/components/responses/service_unavailable"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: billing
        subcategory: enhanced-billing
components:
  schemas:
    actions-billing-usage:
      type: object
      properties:
        total_minutes_used:
          type: integer
          description: The sum of the free and paid GitHub Actions minutes used.
        total_paid_minutes_used:
          type: integer
          description: The total paid GitHub Actions minutes used.
        included_minutes:
          type: integer
          description: The amount of free GitHub Actions minutes available.
        minutes_used_breakdown:
          type: object
          properties:
            UBUNTU:
              type: integer
              description: Total minutes used on Ubuntu runner machines.
            MACOS:
              type: integer
              description: Total minutes used on macOS runner machines.
            WINDOWS:
              type: integer
              description: Total minutes used on Windows runner machines.
            ubuntu_4_core:
              type: integer
              description: Total minutes used on Ubuntu 4 core runner machines.
            ubuntu_8_core:
              type: integer
              description: Total minutes used on Ubuntu 8 core runner machines.
            ubuntu_16_core:
              type: integer
              description: Total minutes used on Ubuntu 16 core runner machines.
            ubuntu_32_core:
              type: integer
              description: Total minutes used on Ubuntu 32 core runner machines.
            ubuntu_64_core:
              type: integer
              description: Total minutes used on Ubuntu 64 core runner machines.
            windows_4_core:
              type: integer
              description: Total minutes used on Windows 4 core runner machines.
            windows_8_core:
              type: integer
              description: Total minutes used on Windows 8 core runner machines.
            windows_16_core:
              type: integer
              description: Total minutes used on Windows 16 core runner machines.
            windows_32_core:
              type: integer
              description: Total minutes used on Windows 32 core runner machines.
            windows_64_core:
              type: integer
              description: Total minutes used on Windows 64 core runner machines.
            macos_12_core:
              type: integer
              description: Total minutes used on macOS 12 core runner machines.
            total:
              type: integer
              description: Total minutes used on all runner machines.
      required:
        - total_minutes_used
        - total_paid_minutes_used
        - included_minutes
        - minutes_used_breakdown
    packages-billing-usage:
      type: object
      properties:
        total_gigabytes_bandwidth_used:
          type: integer
          description: Sum of the free and paid storage space (GB) for GitHuub Packages.
        total_paid_gigabytes_bandwidth_used:
          type: integer
          description: Total paid storage space (GB) for GitHuub Packages.
        included_gigabytes_bandwidth:
          type: integer
          description: Free storage space (GB) for GitHub Packages.
      required:
        - total_gigabytes_bandwidth_used
        - total_paid_gigabytes_bandwidth_used
        - included_gigabytes_bandwidth
    combined-billing-usage:
      type: object
      properties:
        days_left_in_billing_cycle:
          type: integer
          description: Numbers of days left in billing cycle.
        estimated_paid_storage_for_month:
          type: integer
          description: Estimated storage space (GB) used in billing cycle.
        estimated_storage_for_month:
          type: integer
          description: Estimated sum of free and paid storage space (GB) used in billing
            cycle.
      required:
        - days_left_in_billing_cycle
        - estimated_paid_storage_for_month
        - estimated_storage_for_month
    basic-error:
      title: Basic Error
      description: Basic Error
      type: object
      properties:
        message:
          type: string
        documentation_url:
          type: string
        url:
          type: string
        status:
          type: string
    scim-error:
      title: Scim Error
      description: Scim Error
      type: object
      properties:
        message:
          type: string
          nullable: true
        documentation_url:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        status:
          type: integer
        scimType:
          type: string
          nullable: true
        schemas:
          type: array
          items:
            type: string
    billing-usage-report:
      type: object
      properties:
        usageItems:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                description: Date of the usage line item.
              product:
                type: string
                description: Product name.
              sku:
                type: string
                description: SKU name.
              quantity:
                type: integer
                description: Quantity of the usage line item.
              unitType:
                type: string
                description: Unit type of the usage line item.
              pricePerUnit:
                type: number
                description: Price per unit of the usage line item.
              grossAmount:
                type: number
                description: Gross amount of the usage line item.
              discountAmount:
                type: number
                description: Discount amount of the usage line item.
              netAmount:
                type: number
                description: Net amount of the usage line item.
              organizationName:
                type: string
                description: Name of the organization.
              repositoryName:
                type: string
                description: Name of the repository.
            required:
              - date
              - product
              - sku
              - quantity
              - unitType
              - pricePerUnit
              - grossAmount
              - discountAmount
              - netAmount
              - organizationName
    billing-usage-report-user:
      type: object
      properties:
        usageItems:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                description: Date of the usage line item.
              product:
                type: string
                description: Product name.
              sku:
                type: string
                description: SKU name.
              quantity:
                type: integer
                description: Quantity of the usage line item.
              unitType:
                type: string
                description: Unit type of the usage line item.
              pricePerUnit:
                type: number
                description: Price per unit of the usage line item.
              grossAmount:
                type: number
                description: Gross amount of the usage line item.
              discountAmount:
                type: number
                description: Discount amount of the usage line item.
              netAmount:
                type: number
                description: Net amount of the usage line item.
              repositoryName:
                type: string
                description: Name of the repository.
            required:
              - date
              - product
              - sku
              - quantity
              - unitType
              - pricePerUnit
              - grossAmount
              - discountAmount
              - netAmount
  examples:
    actions-billing-usage:
      value:
        total_minutes_used: 305
        total_paid_minutes_used: 0
        included_minutes: 3000
        minutes_used_breakdown:
          UBUNTU: 205
          MACOS: 10
          WINDOWS: 90
    packages-billing-usage:
      value:
        total_gigabytes_bandwidth_used: 50
        total_paid_gigabytes_bandwidth_used: 40
        included_gigabytes_bandwidth: 10
    combined-billing-usage:
      value:
        days_left_in_billing_cycle: 20
        estimated_paid_storage_for_month: 15
        estimated_storage_for_month: 40
    billing-usage-report:
      value:
        usageItems:
          - date: 2023-08-01
            product: Actions
            sku: Actions Linux
            quantity: 100
            unitType: minutes
            pricePerUnit: 0.008
            grossAmount: 0.8
            discountAmount: 0
            netAmount: 0.8
            organizationName: GitHub
            repositoryName: github/example
    billing-usage-report-user:
      value:
        usageItems:
          - date: 2023-08-01
            product: Actions
            sku: Actions Linux
            quantity: 100
            unitType: minutes
            pricePerUnit: 0.008
            grossAmount: 0.8
            discountAmount: 0
            netAmount: 0.8
            repositoryName: user/example
  parameters:
    org:
      name: org
      description: The organization name. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
    billing-usage-report-year:
      name: year
      description: If specified, only return results for a single year. The value of
        `year` is an integer with four digits representing a year. For example,
        `2025`. Default value is the current year.
      in: query
      required: false
      schema:
        type: integer
    billing-usage-report-month:
      name: month
      description: If specified, only return results for a single month. The value of
        `month` is an integer between `1` and `12`. If no year is specified the
        default `year` is used.
      in: query
      required: false
      schema:
        type: integer
    billing-usage-report-day:
      name: day
      description: If specified, only return results for a single day. The value of
        `day` is an integer between `1` and `31`. If no `year` or `month` is
        specified, the default `year` and `month` are used.
      in: query
      required: false
      schema:
        type: integer
    billing-usage-report-hour:
      name: hour
      description: If specified, only return results for a single hour. The value of
        `hour` is an integer between `0` and `23`. If no `year`, `month`, or
        `day` is specified, the default `year`, `month`, and `day` are used.
      in: query
      required: false
      schema:
        type: integer
    username:
      name: username
      description: The handle for the GitHub user account.
      in: path
      required: true
      schema:
        type: string
  responses:
    bad_request:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/basic-error"
        application/scim+json:
          schema:
            $ref: "#/components/schemas/scim-error"
    forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/basic-error"
    internal_error:
      description: Internal Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/basic-error"
    service_unavailable:
      description: Service unavailable
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
              documentation_url:
                type: string
    billing_usage_report_org:
      description: Billing usage report response for an organization
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/billing-usage-report"
          examples:
            default:
              $ref: "#/components/examples/billing-usage-report"
    billing_usage_report_user:
      description: Response when getting a billing usage report
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/billing-usage-report-user"
          examples:
            default:
              $ref: "#/components/examples/billing-usage-report-user"
